name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "main" # Trigger deployment to production on pushes to the main branch
      - "dev"  # Trigger deployment to development on pushes to the dev branch
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.ref_name }}" # Separate concurrency groups for dev and main
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Step 4: Build the project
      - name: Build project
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_SERVICE_KEY: ${{ secrets.VITE_SUPABASE_SERVICE_KEY }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_CLOUDINARY_API_SECRET: ${{ secrets.VITE_CLOUDINARY_API_SECRET }}
          VITE_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
          VITE_BASE_URL: ${{ github.ref_name == 'main' && '/' || '/dev/' }}

      # Step 5: Debugging - List build output
      - name: List build output
        run: ls -la ./dist

      # Step 6: Setup Pages artifact
      - name: Setup Pages artifact
        uses: actions/configure-pages@v4

      # Step 7: Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
       

  deploy:
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'development' }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          branch: ${{ github.ref_name }}
          folder: ${{ github.ref_name == 'main' && '.' || 'dev' }}

